services:
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
  database:
    build: backend/db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  server:
    build: backend/server
    depends_on:
      - database
    ports:
      - "50051:50051"