# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import f1messages_pb2 as f1messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66service.proto\x12\rformulaserver\x1a\x10\x66\x31messages.proto\".\n\x16SimulationStartRequest\x12\x14\n\x0csimulationid\x18\x01 \x01(\x05\"+\n\x13NotifySimulationEnd\x12\x14\n\x0csimulationid\x18\x01 \x01(\x05\" \n\nMessageAck\x12\x12\n\nackmessage\x18\x01 \x01(\t2\xdf\x02\n\x0eMessagePassing\x12U\n\x0fSimulationStart\x12%.formulaserver.SimulationStartRequest\x1a\x19.formulaserver.MessageAck\"\x00\x12P\n\rSimulationEnd\x12\".formulaserver.NotifySimulationEnd\x1a\x19.formulaserver.MessageAck\"\x00\x12\x43\n\x0bGetCarState\x12\x17.formulaserver.CarState\x1a\x19.formulaserver.MessageAck\"\x00\x12_\n\x19GetTimedDriveInstructions\x12%.formulaserver.TimedDriveInstructions\x1a\x19.formulaserver.MessageAck\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMULATIONSTARTREQUEST._serialized_start=51
  _SIMULATIONSTARTREQUEST._serialized_end=97
  _NOTIFYSIMULATIONEND._serialized_start=99
  _NOTIFYSIMULATIONEND._serialized_end=142
  _MESSAGEACK._serialized_start=144
  _MESSAGEACK._serialized_end=176
  _MESSAGEPASSING._serialized_start=179
  _MESSAGEPASSING._serialized_end=530
# @@protoc_insertion_point(module_scope)
