# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x1aTechnionFormulaAV.Messages\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\" \n\x08Vector2D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\".\n\x0eTriggerMessage\x12\x10\n\x08type_url\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\"\xfd\x01\n\x06Header\x12\n\n\x02id\x18\x01 \x01(\r\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10steady_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x06source\x18\x04 \x01(\x0e\x32\".TechnionFormulaAV.Messages.Module\x12<\n\x08triggers\x18\x05 \x03(\x0b\x32*.TechnionFormulaAV.Messages.TriggerMessage\x12\x10\n\x08priority\x18\x06 \x01(\x05\"a\n\x07Message\x12\x32\n\x06header\x18\x01 \x01(\x0b\x32\".TechnionFormulaAV.Messages.Header\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any*\x84\x01\n\x06Module\x12\x12\n\x0eUNKNOWN_MODULE\x10\x00\x12\x12\n\x0e\x43ONTROL_MODULE\x10\x01\x12\x14\n\x10STATE_EST_MODULE\x10\x02\x12\x15\n\x11PERCEPTION_MODULE\x10\x03\x12\x19\n\x15REAL_TIME_DATA_MODULE\x10\x04\x12\n\n\x06SERVER\x10\x05*w\n\x07Mission\x12\x13\n\x0fMISSION_UNKNOWN\x10\x00\x12\x12\n\x0eMISSION_MANUAL\x10\x01\x12\x19\n\x15MISSION_STRAIGHT_LINE\x10\x02\x12\x11\n\rMISSION_EIGHT\x10\x03\x12\x15\n\x11MISSION_ENDURENCE\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODULE._serialized_start=587
  _MODULE._serialized_end=719
  _MISSION._serialized_start=721
  _MISSION._serialized_end=840
  _VECTOR3D._serialized_start=104
  _VECTOR3D._serialized_end=147
  _VECTOR2D._serialized_start=149
  _VECTOR2D._serialized_end=181
  _TRIGGERMESSAGE._serialized_start=183
  _TRIGGERMESSAGE._serialized_end=229
  _HEADER._serialized_start=232
  _HEADER._serialized_end=485
  _MESSAGE._serialized_start=487
  _MESSAGE._serialized_end=584
# @@protoc_insertion_point(module_scope)
