{
 "title": "Live Data",
 "time": { "from": "2023-01-23T22:03:50.575Z", "to": "2023-01-23T22:05:29.848Z" },
 "templating": {
  "list": [
   { "name": "Experiment", "query": "select exp_id from experiments" }
  ]
 },
 "panels": [
  {
   "title": "Acceleration over time for experiment ${Experiment}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "rawSql": "SELECT acceleration, time_stamp AS \"time\" FROM car_state WHERE exp_id = '$Experiment'"
    }
   ]
  },
  {
   "title": "Velocity along x and velocity along y for experiment ${Experiment}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m / s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT velocity_x AS \"velocity x\", velocity_y AS \"velocity y\", time_stamp AS \"time\" FROM car_state WHERE exp_id = '$Experiment'"
    }
   ]
  },
  {
   "title": "Theta for experiment ${Experiment}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "radian" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT theta FROM car_state WHERE exp_id = '$Experiment'"
    }
   ]
  },
  { "title": "Car State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Drive Instructions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Optimal speed over time in experiment ${Experiment}",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "m / s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT optimal_speed, time_stamp \"time\" FROM drive_instructions WHERE exp_id = '$Experiment'"
      }
     ]
    },
    {
     "title": "Steering angle for experiment ${Experiment}",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT steering FROM drive_instructions WHERE exp_id = '$Experiment'"
      }
     ]
    },
    {
     "title": "Brakes over time for experiment ${Experiment}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "rawSql": "SELECT brakes, time_stamp \"time\" FROM drive_instructions WHERE exp_id = '$Experiment'"
      }
     ]
    },
    {
     "title": "Gas over time for experiment ${Experiment}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "rawSql": "SELECT gas, time_stamp \"time\" FROM drive_instructions WHERE exp_id = '$Experiment'"
      }
     ]
    }
   ]
  }
 ]
}