# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\x12\x1aTechnionFormulaAV.Messages\"Y\n\x11\x44riveInstructions\x12\x0b\n\x03gas\x18\x01 \x01(\x02\x12\x0e\n\x06\x62rakes\x18\x02 \x01(\x02\x12\x10\n\x08steering\x18\x03 \x01(\x02\x12\x15\n\roptimal_speed\x18\x04 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRIVEINSTRUCTIONS._serialized_start=45
  _DRIVEINSTRUCTIONS._serialized_end=134
# @@protoc_insertion_point(module_scope)
