# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ground_truth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import perception_pb2 as perception__pb2
import state_est_pb2 as state__est__pb2
import sensors_pb2 as sensors__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ground_truth.proto\x12\x1aTechnionFormulaAV.Messages\x1a\x10perception.proto\x1a\x0fstate_est.proto\x1a\rsensors.proto\x1a\x0c\x63ommon.proto\"\xc1\x01\n\x0bGroundTruth\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\r\x12H\n\x12state_ground_truth\x18\x02 \x01(\x0b\x32,.TechnionFormulaAV.Messages.StateGroundTruth\x12R\n\x17perception_ground_truth\x18\x03 \x01(\x0b\x32\x31.TechnionFormulaAV.Messages.PerceptionGroundTruth\"\x85\x03\n\x10StateGroundTruth\x12\x1a\n\x12has_position_truth\x18\x01 \x01(\x08\x12\x36\n\x08position\x18\x02 \x01(\x0b\x32$.TechnionFormulaAV.Messages.Vector3D\x12!\n\x19has_car_measurments_truth\x18\x03 \x01(\x08\x12\x43\n\x0f\x63\x61r_measurments\x18\x04 \x01(\x0b\x32*.TechnionFormulaAV.Messages.CarMeasurments\x12!\n\x19has_imu_measurments_truth\x18\x05 \x01(\x08\x12\x43\n\x0fimu_measurments\x18\x06 \x01(\x0b\x32*.TechnionFormulaAV.Messages.IMUMeasurments\x12\x17\n\x0fhas_cones_truth\x18\x07 \x01(\x08\x12\x34\n\x05\x63ones\x18\x08 \x03(\x0b\x32%.TechnionFormulaAV.Messages.StateConeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ground_truth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUNDTRUTH._serialized_start=115
  _GROUNDTRUTH._serialized_end=308
  _STATEGROUNDTRUTH._serialized_start=311
  _STATEGROUNDTRUTH._serialized_end=700
# @@protoc_insertion_point(module_scope)
