# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perception.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10perception.proto\x12\x1aTechnionFormulaAV.Messages\x1a\x0c\x63ommon.proto\"4\n\rFramePosition\x12\t\n\x01u\x18\x01 \x01(\r\x12\t\n\x01v\x18\x02 \x01(\r\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x04\"\x80\x01\n\x04\x43one\x12\x0f\n\x07\x63one_id\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\x32\n\x04type\x18\x05 \x01(\x0e\x32$.TechnionFormulaAV.Messages.ConeType\x12\x12\n\nconfidence\x18\x06 \x01(\x02\"\xfc\x01\n\x0b\x42oundingBox\x12\x0f\n\x07\x63one_id\x18\x01 \x01(\r\x12\x32\n\x04type\x18\x02 \x01(\x0e\x32$.TechnionFormulaAV.Messages.ConeType\x12\x0e\n\x06height\x18\x03 \x01(\x02\x12\r\n\x05width\x18\x04 \x01(\x02\x12\x0e\n\x06length\x18\x05 \x01(\x02\x12\x41\n\x0e\x66rame_position\x18\x06 \x01(\x0b\x32).TechnionFormulaAV.Messages.FramePosition\x12\x36\n\x08position\x18\x07 \x01(\x0b\x32$.TechnionFormulaAV.Messages.Vector3D\":\n\x07\x43oneMap\x12/\n\x05\x63ones\x18\x01 \x03(\x0b\x32 .TechnionFormulaAV.Messages.Cone\"o\n\x15PerceptionGroundTruth\x12 \n\x18has_bounding_boxes_truth\x18\x01 \x01(\x08\x12\x34\n\x03\x62\x62s\x18\x02 \x03(\x0b\x32\'.TechnionFormulaAV.Messages.BoundingBox*L\n\x08\x43oneType\x12\x0f\n\x0bUnknownType\x10\x00\x12\n\n\x06Yellow\x10\x01\x12\x08\n\x04\x42lue\x10\x02\x12\n\n\x06Orange\x10\x03\x12\r\n\tOrangeBig\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perception_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONETYPE._serialized_start=675
  _CONETYPE._serialized_end=751
  _FRAMEPOSITION._serialized_start=62
  _FRAMEPOSITION._serialized_end=114
  _CONE._serialized_start=117
  _CONE._serialized_end=245
  _BOUNDINGBOX._serialized_start=248
  _BOUNDINGBOX._serialized_end=500
  _CONEMAP._serialized_start=502
  _CONEMAP._serialized_end=560
  _PERCEPTIONGROUNDTRUTH._serialized_start=562
  _PERCEPTIONGROUNDTRUTH._serialized_end=673
# @@protoc_insertion_point(module_scope)
