# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x1aTechnionFormulaAV.Messages\x1a\x0c\x63ommon.proto\"\r\n\x0b\x45xitMessage\"\x14\n\x12\x43onnectionApproved\"\x0f\n\rSwitchToASOff\"H\n\x10SwitchToASDReady\x12\x34\n\x07mission\x18\x01 \x01(\x0e\x32#.TechnionFormulaAV.Messages.Mission\"\x13\n\x11SwitchToASDriving\"\x14\n\x12SwitchToASFinished\"\x15\n\x13SwitchToASEmergency\"\x14\n\x12\x46inishedControlLap\"\x12\n\x10\x46inishedFinalLapb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXITMESSAGE._serialized_start=58
  _EXITMESSAGE._serialized_end=71
  _CONNECTIONAPPROVED._serialized_start=73
  _CONNECTIONAPPROVED._serialized_end=93
  _SWITCHTOASOFF._serialized_start=95
  _SWITCHTOASOFF._serialized_end=110
  _SWITCHTOASDREADY._serialized_start=112
  _SWITCHTOASDREADY._serialized_end=184
  _SWITCHTOASDRIVING._serialized_start=186
  _SWITCHTOASDRIVING._serialized_end=205
  _SWITCHTOASFINISHED._serialized_start=207
  _SWITCHTOASFINISHED._serialized_end=227
  _SWITCHTOASEMERGENCY._serialized_start=229
  _SWITCHTOASEMERGENCY._serialized_end=250
  _FINISHEDCONTROLLAP._serialized_start=252
  _FINISHEDCONTROLLAP._serialized_end=272
  _FINISHEDFINALLAP._serialized_start=274
  _FINISHEDFINALLAP._serialized_end=292
# @@protoc_insertion_point(module_scope)
